"""
Reads a workbook this app generated back into LineItems, for the
"add a new FY to an existing commonsize" option.

Only input cells are read (the Sch. item rows and the few fixed input cells);
formulas are ignored, so nothing needs Excel to have calculated them. Because
the writer places every value into a known schedule row, each item comes back
with `schedule_override` set and goes to the same row again on re-generation.
"""

import re
from dataclasses import dataclass, field

import openpyxl

from config.schedule_map import ALL_SCHEDULES, FY_COLUMN_MAP, SHEET_NAME
from core.models import LineItem
from core.routing import CHANGE_IN_INVENTORIES

PNL_SCHEDULES = {
    "Revenue", "Other Income", "COGS-Purchase", "COGS-Manufacturing", "Employee Benefit Expenses",
    "Administrative Expenses", "Selling & Distribution Expenses", "Depreciation", "Finance Costs", "Tax Expense",
}
SINGLE_CELL_SCHEDULES = {
    "Share Capital", "Securities Premium", "Reserves Adjustments", "Deferred Tax Assets", "Deferred Tax Liabilities",
    "COGS-Purchase", "Reserves and Surplus",
}
_YELLOW = {"00FFFF00", "FFFFFF00"}
_STOCK_ROWS = ("Opening Stock (Change in Inventories)", "Closing Stock (Change in Inventories)")


@dataclass
class WorkbookData:
    company: str = ""
    equity_shares: str = ""
    fy_columns: list = field(default_factory=list)
    items: list = field(default_factory=list)
    reported_pat: dict = field(default_factory=dict)   # rupees
    warnings: list = field(default_factory=list)


def _values(ws, row):
    out = {}
    for fy, col in FY_COLUMN_MAP.items():
        v = ws[f"{col}{row}"].value
        out[fy] = float(v) if isinstance(v, (int, float)) and not isinstance(v, bool) else None
    return out


def _has_value(values):
    return any(v for v in values.values())


def read_workbook(path):
    wb = openpyxl.load_workbook(path)
    if SHEET_NAME not in wb.sheetnames or "IS" not in wb.sheetnames:
        raise ValueError("This does not look like a workbook generated by this app (Sch./IS sheets not found).")
    ws = wb[SHEET_NAME]
    # the row layout must be the current template's, else values would be read from the wrong rows
    moved = [key for key, s in ALL_SCHEDULES.items()
             if s["pattern"] == "total_last" and s["insertable"]
             and str(ws.cell(s["total_row"], 2).value or "").strip().lower()[:5] != "total"]
    if moved:
        raise ValueError("This workbook was made with an older version of the template, so its rows are in different "
                         "places. Please generate it again from the original financials, then add the new year.")
    data = WorkbookData(company=str(wb["IS"]["B2"].value or ""))

    share_label = str(ws[f"B{ALL_SCHEDULES['Share Capital']['first_item_row']}"].value or "")
    m = re.match(r"\s*([\d,\.]+)\s+equity shares", share_label)
    data.equity_shares = m.group(1) if m else ""

    for key, sched in ALL_SCHEDULES.items():
        if key in _STOCK_ROWS:
            continue
        statement = "P&L" if key in PNL_SCHEDULES else "BS"
        rows = [sched["first_item_row"]] if key in SINGLE_CELL_SCHEDULES else range(sched["first_item_row"], sched["last_item_row"] + 1)
        for r in rows:
            values = _values(ws, r)
            if key == "Reserves and Surplus":
                values = {fy: v for fy, v in values.items() if v is not None}   # only the earliest year is an input
                values = {fy: values.get(fy) for fy in FY_COLUMN_MAP}
            if not _has_value(values):
                continue
            label = str(ws.cell(r, 2).value or key)
            fill = ws.cell(r, 2).fill
            is_new = bool(fill and fill.fill_type == "solid" and str(fill.start_color.rgb) in _YELLOW)
            comment = ws.cell(r, 2).comment
            data.items.append(LineItem(
                statement=statement, line_item=label, statement_tag="", fy_values=values,
                source="workbook", is_new=is_new, schedule_override=key,
                pdf_heading=(comment.text if comment else ""), confidence="Matched" if not is_new else "Uncertain (new item)",
            ))

    opening, closing = (ALL_SCHEDULES[k]["first_item_row"] for k in _STOCK_ROWS)
    op, cl = _values(ws, opening), _values(ws, closing)
    change = {fy: ((op[fy] or 0.0) - (cl[fy] or 0.0)) if (op[fy] is not None or cl[fy] is not None) else None
              for fy in FY_COLUMN_MAP}
    if _has_value(change):
        data.items.append(LineItem(statement="P&L", line_item="Change in inventories", statement_tag="Change in Inventories",
                                   fy_values=change, source="workbook", schedule_override=CHANGE_IN_INVENTORIES))

    for fy, col in FY_COLUMN_MAP.items():
        v = wb["IS"][f"{col}24"].value
        if isinstance(v, (int, float)):
            data.reported_pat[fy] = float(v) * 1_000_000

    data.fy_columns = [fy for fy in FY_COLUMN_MAP
                       if any(i.fy_values.get(fy) for i in data.items if i.schedule_override != "Reserves and Surplus")]
    return data


def merge_new_year(existing, new_items, new_fy, new_reported_pat=None):
    """
    Add one financial year to an existing workbook's data. Only `new_fy` is taken from the new items (a PDF
    also carries the comparative year, which would otherwise overwrite figures already in the workbook).
    The new year must come after the latest year already present, because the template opens the first year
    from an input and every later year from the previous closing balance.
    Returns (items, fy_columns, reported_pat, warnings).
    """
    warnings = []
    if new_fy not in FY_COLUMN_MAP:
        raise ValueError(f"{new_fy} is outside the template's columns ({', '.join(FY_COLUMN_MAP)}).")
    if existing.fy_columns and new_fy in existing.fy_columns:
        raise ValueError(f"{new_fy} is already in the workbook; updating an existing year is not supported.")
    order = list(FY_COLUMN_MAP)
    if existing.fy_columns and order.index(new_fy) < order.index(existing.fy_columns[-1]):
        raise ValueError(f"{new_fy} is earlier than the latest year in the workbook ({existing.fy_columns[-1]}); "
                         "only a later year can be added.")
    if existing.fy_columns and order.index(new_fy) != order.index(existing.fy_columns[-1]) + 1:
        warnings.append(f"{new_fy} does not directly follow {existing.fy_columns[-1]}; the years in between are blank, "
                        "so the reserves carried forward will not reconcile.")

    merged = list(existing.items)
    for item in new_items:
        value = item.fy_values.get(new_fy)
        if value is None or item.schedule_override == "Reserves and Surplus":
            continue
        clone = LineItem(**{**item.__dict__, "fy_values": {fy: (value if fy == new_fy else None) for fy in FY_COLUMN_MAP}})
        if item.statement_tag == "Opening Reserves":
            continue   # the new year opens from the previous closing balance
        merged.append(clone)
    reported = dict(existing.reported_pat)
    if new_reported_pat and new_reported_pat.get(new_fy) is not None:
        reported[new_fy] = new_reported_pat[new_fy]
    return merged, sorted(set(existing.fy_columns) | {new_fy}, key=order.index), reported, warnings
